INSERT INTO Players (Name, Country, Post, Goals)
VALUES
("Alireza Beiranvand", "Iran", "Goalkeeper", 0),
("Sardar Azmoun", "Iran", "Forward", 24),
("Reza Quchan Nejad", "Iran", "Forward", 16),
("Lionel Messi", "Argentina", "Forward", 40),
("Cristiano Ronaldo", "Portugal", "Forward", 40),
("Sergio Ramos", "Spain", "Defender", 32),
("Bernardo Silva", "Portugal", "Halfback", 20),
("Ramin Firooz", "Portugal", "Halfback", 70),
("Bernardo Gilba", "Portugal", "Halfback", 34),
("Silva Bernardo", "Portugal", "Halfback", 12),
("Ted Silvanova", "Iran", "Forward", 4),
("Firooz Ramin", "USA", "Forward", 90),
("Sasan Masan", "Portugal", "Halfback", 43),
("Nina Bana", "Portugal", "Halfback", 44),
("Dodo Bada", "Portugal", "Halfback", 34),
("Agata Magata", "Portugal", "Halfback", 43),
("Ali Daiee", "Iran", "Forward", 87),
("Hermann Firooz", "USA", "Halfback", 99);